엔드포인트 및 모델 추가
solvedac/unofficial-documentation pull request #72
Opened 2024-05-02 18:54 UTC by w8385

새로이 추가됐거나 누락된 엔드포인트들을 추가합니다.

5d2e331a5c2a9b551c9a71a46e00e4e0ceaa7c46: prettier line operator를 `CRLF`로 고정하였습니다.

### Endpoints
- /user/additional_info
  - 해당 핸들의 사용자 개인정보를 가져옵니다.

### Models
- UserAdditianlInfo
  - solved.ac 사용자 개인정보입니다.

2024-07-20 18:51 UTC, RanolP requested changes
리뷰가 늦어져서 죄송합니다.
코멘트들 확인하시고, 수정할 부분 수정해주시거나 답변 남겨주시면 감사하겠습니당

2024-07-20 18:51 UTC, RanolP commented on src/models/Post.tsp
> + * solved.ac의 도움말입니다.
p3: 이용 약관 등 다양한 목적으로 사용할 수 있다보니 도움말보다는 게시글이 적합할 것 같습니다.

2024-07-20 18:51 UTC, RanolP commented on src/models/Post.tsp
> +   * 도움말가 작성된 언어입니다.
p3:
```suggestion
   * 도움말이 작성된 언어입니다.
```

2024-07-20 18:51 UTC, RanolP commented on src/models/Post.tsp
> +   * 도움말의 타입입니다.
type: markdown 등이 내려오는 걸로 보아 내용의 타입이라고 설명하면 더 도움이 될 것 같습니다

2024-07-20 18:51 UTC, RanolP commented on src/models/Post.tsp
> +   * @example "이 규칙은 2020년 3월 1일부터 유효합니다.\n\n## 1\\. 난이도 기여\n\n난이도 기여는 난이도 기여 가이드라인을 기반으로 자신이 해당 문제를 해결하고 느낀 난이도를 솔직하게 표현해야 합니다. 다음과 같은 난이도 기여는 운영진 판단 하에 임의로 삭제될 수 있습니다.\n\n**a**. 특정 문제에 다른 이용자 대부분이
잡담) 이거 example 안 보이는데 아마 제가 typespec patch 잘못한듯... 나중에 고쳐보겠습니다

2024-07-20 18:51 UTC, RanolP commented on src/operations/post/show.tsp
> + * 해당 제목의 도움말을 가져옵니다.
여기도 src/models/Post.tsp와 동일하게, 도움말보다 게시글이 적합할 것 같습니다

2024-07-20 18:51 UTC, RanolP commented on src/operations/user/class_stats.tsp
> +   * @example
잡담) 이거 지금 예시 안 보이고 있을 거 같은데 나중에 제가 시간 나면 고칠게요 (인덴트 문제)
example 저거 어떻게 쓰는지 설명을 추가해야하는디...

2024-07-20 18:51 UTC, RanolP commented on src/operations/user/contribution_stats.tsp
> +   *{
잡담) 여기도 마찬가지로 인덴트 때문에 examle 안 보일텐데 제가 나중에 고칠게요

2024-07-26 10:39 UTC, w8385 commented on .prettierrc
> +  "endOfLine": "crlf"
/scripts/git-hooks/pre-commit 실행시 `LF will be replaced by CRLF` 에러가 발생했었습니다.
지금 확인한 바로는 모든 파일이 LF로 되어있는데, 다시 확인 후 변경토록 하겠습니다.

2024-07-26 11:09 UTC, w8385 commented on .prettierrc
> +  "endOfLine": "crlf"
[83d0d13](https://github.com/solvedac/unofficial-documentation/pull/72/commits/83d0d13f389f171f920e7b728f39f8b11a306e34) 에서 수정하였습니다!

2024-07-26 11:09 UTC, w8385 commented on src/operations/ranking/arena_in_organization.tsp
> +op getArenaInOrganizationRankingByACRating(
[7e740af](https://github.com/solvedac/unofficial-documentation/pull/72/commits/7e740afd3d8f2f6011f31278fabdf9065a3ab0db) 에서 수정하였습니다!

2024-07-26 11:10 UTC, w8385 commented on src/operations/ranking/in_organization.tsp
> +op getInOrganizationRankingByACRating(
[d3da6cb](https://github.com/solvedac/unofficial-documentation/pull/72/commits/d3da6cbf01827671abb9f7767c44b5366b3873bc) 에서 수정하였습니다!

2024-07-26 11:10 UTC, w8385 commented on src/operations/user/additional_info.tsp
> + * 해당 핸들의 사용자 개인정보를 가져옵니다.
[6ca1890](https://github.com/solvedac/unofficial-documentation/pull/72/commits/6ca189008de6a5f0b4d723db9e3e42016f0ffbdb) 부가 정보로 번역 수정하였습니다!

2024-07-26 11:10 UTC, w8385 commented on src/models/Post.tsp
> + * solved.ac의 도움말입니다.
[d528af8](https://github.com/solvedac/unofficial-documentation/pull/72/commits/d528af86c22c216b80a503f5b4eeb3eb64de87c6) 게시글로 번역 수정하였습니다!

2024-07-26 11:10 UTC, w8385 commented on src/models/Post.tsp
> +   * 도움말가 작성된 언어입니다.
[d528af8](https://github.com/solvedac/unofficial-documentation/pull/72/commits/d528af86c22c216b80a503f5b4eeb3eb64de87c6) 에서 수정하였습니다!

2024-07-26 11:11 UTC, w8385 commented on src/models/Post.tsp
> +   * 도움말의 타입입니다.
[d528af8](https://github.com/solvedac/unofficial-documentation/pull/72/commits/d528af86c22c216b80a503f5b4eeb3eb64de87c6) 에서 수정하였습니다!

2024-07-26 11:13 UTC, w8385 commented on src/models/Post.tsp
> +   * @example "이 규칙은 2020년 3월 1일부터 유효합니다.\n\n## 1\\. 난이도 기여\n\n난이도 기여는 난이도 기여 가이드라인을 기반으로 자신이 해당 문제를 해결하고 느낀 난이도를 솔직하게 표현해야 합니다. 다음과 같은 난이도 기여는 운영진 판단 하에 임의로 삭제될 수 있습니다.\n\n**a**. 특정 문제에 다른 이용자 대부분이
실행중에 이렇게 에러 메시지가 뜨더라구요. 너무 길어서 그런걸까요?
```
[watch] Error: Unterminated string in JSON at position 770
[watch] "이 규칙은 2020년 3월 1일부터 유효합니다.\n\n## 1\\. 난이도 기여\n\n난이도 기여는 난이도 기여 가이드라인을 기반으로 자신이 해당 문제를 해결하고 느낀 난이도를 솔직하게 표현해야 합니다. 다음과 같은 난이도 기여는 운영진 판 
단 하에 임의로 삭제될 수 있습니다.\n\n**a**. 특정 문제에 다른 이용자 대부분이 납득하기 힘든 난이도를 매긴 경우\n\n* 예: 1000번 문제에 Ruby I을 기여, 8481번 문제에 Bronze V를 기여\n* 2020년 이전 기여 중 Platinum과 Silver를 헷갈린
기여는 예외로 합니다.\n* 이와 같은 기여를 자신의 티어를 올릴 목적으로 한 경우, 기여가 삭제되는 것은 물론 해당 문제에 대한 경험치가 영구적으로 반영되지 않게 될 수 있습니다.\n\n**b**. 특정 문제를 해결하는 것과 관련이 없거나 도움  
이 전혀 되지 않는 태그를 단 경우\n* 예: 1003번 문제에 tag:dijkstra를 닮\n* 난이도 기여 전체를 삭제하는 대신, 해당 태그만 삭제될 수도 있습니다.\n* 문제와 관련 없는 태그를 납득하기 힘들 정도로 많이 달았다면 이용자에게 혼란을 주기 
위함이라고 판단될 수 있습니다.\n\n**c**. 난이도 기여 경험치를 얻기 위한 목적으로, 자동화 스크립트 등을 사용해 자신이 푼 문제에 난이도를 일괄적으로 매기는 경우\n\n**d**. 경험치를 얻기 위한 목적으로, 정상적이지 않은 방법으로 난이 도 기여를 한 경우\n* 정상적이지 않은 방법으로 난이도 기여가 가능함을 발견한 경우 shift is not a valid json.
```

2024-07-26 11:14 UTC, w8385 commented on src/operations/user/class_stats.tsp
> +   * @example
넵 model에서 끌어오는 거 말고 직접 example 넣는 건 잘 모르겠어요..

2024-07-26 11:14 UTC, w8385 commented on src/operations/user/contribution_stats.tsp
> +   *{
확인했습니다!

2024-07-27 18:32 UTC, RanolP commented on src/models/Post.tsp
> +   * @example "이 규칙은 2020년 3월 1일부터 유효합니다.\n\n## 1\\. 난이도 기여\n\n난이도 기여는 난이도 기여 가이드라인을 기반으로 자신이 해당 문제를 해결하고 느낀 난이도를 솔직하게 표현해야 합니다. 다음과 같은 난이도 기여는 운영진 판단 하에 임의로 삭제될 수 있습니다.\n\n**a**. 특정 문제에 다른 이용자 대부분이
shift@solved.ac 때문인 거 같은데 저거 수정이 쉽게 될런가 모르겠네요 ㅠ

2024-07-27 18:33 UTC, RanolP approved these changes

2024-07-27 18:33 UTC, RanolP commented
수고하셨습니다!!

2024-07-27 18:33 UTC, merged